/*
 * libFuzzer harness for ngx_http_error_abuse_validate_snapshot().
 *
 * Why this target: it parses an untrusted on-disk snapshot file — bytes
 * an attacker (or corruption) can put under the persistence path — doing
 * raw pointer arithmetic against p / last and ngx_memcpy()ing a
 * fixed-size record straight off the buffer. It is the gate that load()
 * trusts: if validate returns NGX_OK, load() walks the SAME buffer with
 * the SAME stride and reads key_len + event_count*8 payload bytes without
 * re-deriving the bound. So the security contract is:
 *
 *   validate_snapshot() == NGX_OK  =>  every byte load() will later read
 *                                      lies within [orig_p, last).
 *
 * This harness fuzzes that gate two ways at once:
 *   1. ASAN/UBSAN on validate_snapshot itself catches any OOB read or
 *      overflow in the validator's own walk.
 *   2. When validate returns NGX_OK, the harness re-walks the buffer with
 *      load()'s exact stride and touches every payload byte through a
 *      volatile sink. ASAN then turns ANY gap between what validate
 *      accepts and what load() reads into an immediate heap-buffer-
 *      overflow — a hard regression gate on the two staying in lockstep.
 *
 * The real function lives in ../ngx_http_error_abuse_module.c and depends
 * on the nginx tree. fuzz/extract_parser.sh slices just that function into
 * generated_parser.inc at build time, so we always fuzz the SHIPPED code
 * with no copy drift. ngx_shim.h provides the tiny nginx surface it needs.
 *
 * Build (see fuzz/build.sh):
 *   clang -g -O1 -fsanitize=fuzzer,address,undefined \
 *       fuzz_snapshot.c -o fuzz_snapshot
 */

#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "ngx_shim.h"

/* Generated by fuzz/extract_parser.sh from
 * ../ngx_http_error_abuse_module.c — the verbatim body of
 * ngx_http_error_abuse_validate_snapshot(). */
#include "generated_parser.inc"

/* Keep the loop count bounded so a 4-byte "records" field of 0xffffffff
 * cannot make the validator spin; the real header->records is bounded by
 * the file fitting in the shm zone, and each record consumes >= 20 bytes
 * so the walk is size-bounded anyway, but cap it explicitly for speed. */
#define FUZZ_MAX_RECORDS  100000u

int
LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)
{
    /*
     * Carve the fuzzer-controlled control fields off the front:
     *   [0..4)  records  (uint32, little-endian)
     *   [4]     threshold lever (mapped into a small range so the
     *           event_count > threshold reject path is reachable)
     * The remainder is the snapshot payload handed to the validator as
     * the [p, last) byte range — exactly what load() passes after the
     * file header.
     */
    if (size < 5) {
        return 0;
    }

    uint32_t records = (uint32_t) data[0]
                     | ((uint32_t) data[1] << 8)
                     | ((uint32_t) data[2] << 16)
                     | ((uint32_t) data[3] << 24);
    if (records > FUZZ_MAX_RECORDS) {
        records = FUZZ_MAX_RECORDS;
    }

    ngx_http_error_abuse_zone_t zone;
    /* 0..255 threshold; covers event_count==0, the boundary, and reject. */
    zone.threshold = (ngx_uint_t) data[4];

    size_t  payload_len = size - 5;
    /* Allocate EXACTLY payload_len (1 byte when zero) with no trailing
     * slack, so any read at or past `last` is an ASAN heap overflow. */
    size_t  alloc = payload_len ? payload_len : 1;
    u_char *buf = (u_char *) malloc(alloc);
    if (buf == NULL) {
        return 0;
    }
    if (payload_len) {
        memcpy(buf, data + 5, payload_len);
    }

    u_char *p    = buf;
    u_char *last = buf + payload_len;

    ngx_int_t rc = ngx_http_error_abuse_validate_snapshot(&zone, p, last,
                                                          records);

    if (rc != NGX_OK && rc != NGX_ERROR) {
        __builtin_trap();
    }

    if (rc == NGX_OK) {
        /*
         * Replay load()'s stride over the validated buffer and read every
         * byte it would read. If validate accepted a buffer that load()
         * would over-read, ASAN fires here. Mirrors the consumption loop
         * in ngx_http_error_abuse_load().
         */
        volatile uint8_t sink = 0;
        ngx_http_error_abuse_file_record_t rec;

        for (uint32_t i = 0; i < records; i++) {
            if ((size_t) (last - p) < sizeof(rec)) {
                __builtin_trap();   /* validate said OK but record truncated */
            }
            memcpy(&rec, p, sizeof(rec));
            p += sizeof(rec);

            size_t need = (size_t) rec.key_len
                        + (size_t) rec.event_count * sizeof(int64_t);
            if ((size_t) (last - p) < need) {
                __builtin_trap();   /* validate said OK but payload short */
            }
            for (size_t k = 0; k < need; k++) {
                sink ^= p[k];
            }
            p += need;
        }
        /* validate's contract: exact consumption, p lands on last. */
        if (p != last) {
            __builtin_trap();
        }
        (void) sink;
    }

    free(buf);
    return 0;
}
